spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: toons-api
  r2dbc:
    url: ${R2DBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: ${FLYWAY_URL}
    locations: classpath:db/migration

google:
  client_id: ${GOOGLE_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    org:
      springframework:
        r2dbc: ${LOG_LEVEL_R2DBC:INFO}