spring:
  mail:
    host: ${SMTP_HOST}
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  config:
    import: optional:file:.env[.properties]
  application:
    name: toons-api
  r2dbc:
    url: ${R2DBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: ${JDBC_URL}
    locations: classpath:db/migration
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.scheduler.instanceName: MyScheduler
      org.quartz.threadPool.threadCount: 3
    jdbc:
      initialize-schema: never


google:
  client_id: ${GOOGLE_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    org:
      springframework:
        r2dbc: ${LOG_LEVEL_R2DBC:INFO}